/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseCheckInResponse,
  ApiResponseCheckOutResponse,
} from '../models/index';
import {
    ApiResponseCheckInResponseFromJSON,
    ApiResponseCheckInResponseToJSON,
    ApiResponseCheckOutResponseFromJSON,
    ApiResponseCheckOutResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class AttendanceApi extends runtime.BaseAPI {

    /**
     * Check-in as a student
     */
    async checkInRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseCheckInResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/attendance/check-in`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseCheckInResponseFromJSON(jsonValue));
    }

    /**
     * Check-in as a student
     */
    async checkIn(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseCheckInResponse> {
        const response = await this.checkInRaw(initOverrides);
        return await response.value();
    }

    /**
     * Check-out as a student
     */
    async checkOutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseCheckOutResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/attendance/check-out`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseCheckOutResponseFromJSON(jsonValue));
    }

    /**
     * Check-out as a student
     */
    async checkOut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseCheckOutResponse> {
        const response = await this.checkOutRaw(initOverrides);
        return await response.value();
    }

}
