/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionDetailDto } from './QuestionDetailDto';
import {
    QuestionDetailDtoFromJSON,
    QuestionDetailDtoFromJSONTyped,
    QuestionDetailDtoToJSON,
    QuestionDetailDtoToJSONTyped,
} from './QuestionDetailDto';

/**
 * 
 * @export
 * @interface ApiResponseQuestionDetailDto
 */
export interface ApiResponseQuestionDetailDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseQuestionDetailDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseQuestionDetailDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseQuestionDetailDto
     */
    statusCode: number;
    /**
     * 
     * @type {QuestionDetailDto}
     * @memberof ApiResponseQuestionDetailDto
     */
    data?: QuestionDetailDto | null;
}

/**
 * Check if a given object implements the ApiResponseQuestionDetailDto interface.
 */
export function instanceOfApiResponseQuestionDetailDto(value: object): value is ApiResponseQuestionDetailDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseQuestionDetailDtoFromJSON(json: any): ApiResponseQuestionDetailDto {
    return ApiResponseQuestionDetailDtoFromJSONTyped(json, false);
}

export function ApiResponseQuestionDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseQuestionDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : QuestionDetailDtoFromJSON(json['data']),
    };
}

export function ApiResponseQuestionDetailDtoToJSON(json: any): ApiResponseQuestionDetailDto {
    return ApiResponseQuestionDetailDtoToJSONTyped(json, false);
}

export function ApiResponseQuestionDetailDtoToJSONTyped(value?: ApiResponseQuestionDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': QuestionDetailDtoToJSON(value['data']),
    };
}

