/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultipleChoiceOptionDto } from './MultipleChoiceOptionDto';
import {
    MultipleChoiceOptionDtoFromJSON,
    MultipleChoiceOptionDtoFromJSONTyped,
    MultipleChoiceOptionDtoToJSON,
    MultipleChoiceOptionDtoToJSONTyped,
} from './MultipleChoiceOptionDto';

/**
 * 
 * @export
 * @interface ApiResponseMultipleChoiceOptionDto
 */
export interface ApiResponseMultipleChoiceOptionDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseMultipleChoiceOptionDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseMultipleChoiceOptionDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseMultipleChoiceOptionDto
     */
    statusCode: number;
    /**
     * 
     * @type {MultipleChoiceOptionDto}
     * @memberof ApiResponseMultipleChoiceOptionDto
     */
    data?: MultipleChoiceOptionDto;
}

/**
 * Check if a given object implements the ApiResponseMultipleChoiceOptionDto interface.
 */
export function instanceOfApiResponseMultipleChoiceOptionDto(value: object): value is ApiResponseMultipleChoiceOptionDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseMultipleChoiceOptionDtoFromJSON(json: any): ApiResponseMultipleChoiceOptionDto {
    return ApiResponseMultipleChoiceOptionDtoFromJSONTyped(json, false);
}

export function ApiResponseMultipleChoiceOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseMultipleChoiceOptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : MultipleChoiceOptionDtoFromJSON(json['data']),
    };
}

export function ApiResponseMultipleChoiceOptionDtoToJSON(json: any): ApiResponseMultipleChoiceOptionDto {
    return ApiResponseMultipleChoiceOptionDtoToJSONTyped(json, false);
}

export function ApiResponseMultipleChoiceOptionDtoToJSONTyped(value?: ApiResponseMultipleChoiceOptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': MultipleChoiceOptionDtoToJSON(value['data']),
    };
}

