/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfoResponseSubjectDto } from './PageInfoResponseSubjectDto';
import {
    PageInfoResponseSubjectDtoFromJSON,
    PageInfoResponseSubjectDtoFromJSONTyped,
    PageInfoResponseSubjectDtoToJSON,
    PageInfoResponseSubjectDtoToJSONTyped,
} from './PageInfoResponseSubjectDto';

/**
 * 
 * @export
 * @interface ApiResponsePageInfoResponseSubjectDto
 */
export interface ApiResponsePageInfoResponseSubjectDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseSubjectDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseSubjectDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageInfoResponseSubjectDto
     */
    statusCode: number;
    /**
     * 
     * @type {PageInfoResponseSubjectDto}
     * @memberof ApiResponsePageInfoResponseSubjectDto
     */
    data?: PageInfoResponseSubjectDto | null;
}

/**
 * Check if a given object implements the ApiResponsePageInfoResponseSubjectDto interface.
 */
export function instanceOfApiResponsePageInfoResponseSubjectDto(value: object): value is ApiResponsePageInfoResponseSubjectDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponsePageInfoResponseSubjectDtoFromJSON(json: any): ApiResponsePageInfoResponseSubjectDto {
    return ApiResponsePageInfoResponseSubjectDtoFromJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseSubjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageInfoResponseSubjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : PageInfoResponseSubjectDtoFromJSON(json['data']),
    };
}

export function ApiResponsePageInfoResponseSubjectDtoToJSON(json: any): ApiResponsePageInfoResponseSubjectDto {
    return ApiResponsePageInfoResponseSubjectDtoToJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseSubjectDtoToJSONTyped(value?: ApiResponsePageInfoResponseSubjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': PageInfoResponseSubjectDtoToJSON(value['data']),
    };
}

