/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponseString
 */
export interface ApiResponseString {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseString
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseString
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseString
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseString
     */
    data?: string | null;
}

/**
 * Check if a given object implements the ApiResponseString interface.
 */
export function instanceOfApiResponseString(value: object): value is ApiResponseString {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseStringFromJSON(json: any): ApiResponseString {
    return ApiResponseStringFromJSONTyped(json, false);
}

export function ApiResponseStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseString {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ApiResponseStringToJSON(json: any): ApiResponseString {
    return ApiResponseStringToJSONTyped(json, false);
}

export function ApiResponseStringToJSONTyped(value?: ApiResponseString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': value['data'],
    };
}

