/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubjectDto } from './SubjectDto';
import {
    SubjectDtoFromJSON,
    SubjectDtoFromJSONTyped,
    SubjectDtoToJSON,
    SubjectDtoToJSONTyped,
} from './SubjectDto';

/**
 * 
 * @export
 * @interface ApiResponseSubjectDto
 */
export interface ApiResponseSubjectDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseSubjectDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseSubjectDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseSubjectDto
     */
    statusCode: number;
    /**
     * 
     * @type {SubjectDto}
     * @memberof ApiResponseSubjectDto
     */
    data?: SubjectDto | null;
}

/**
 * Check if a given object implements the ApiResponseSubjectDto interface.
 */
export function instanceOfApiResponseSubjectDto(value: object): value is ApiResponseSubjectDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseSubjectDtoFromJSON(json: any): ApiResponseSubjectDto {
    return ApiResponseSubjectDtoFromJSONTyped(json, false);
}

export function ApiResponseSubjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseSubjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : SubjectDtoFromJSON(json['data']),
    };
}

export function ApiResponseSubjectDtoToJSON(json: any): ApiResponseSubjectDto {
    return ApiResponseSubjectDtoToJSONTyped(json, false);
}

export function ApiResponseSubjectDtoToJSONTyped(value?: ApiResponseSubjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': SubjectDtoToJSON(value['data']),
    };
}

