/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfoResponseQuestionDetailDto } from './PageInfoResponseQuestionDetailDto';
import {
    PageInfoResponseQuestionDetailDtoFromJSON,
    PageInfoResponseQuestionDetailDtoFromJSONTyped,
    PageInfoResponseQuestionDetailDtoToJSON,
    PageInfoResponseQuestionDetailDtoToJSONTyped,
} from './PageInfoResponseQuestionDetailDto';

/**
 * 
 * @export
 * @interface ApiResponsePageInfoResponseQuestionDetailDto
 */
export interface ApiResponsePageInfoResponseQuestionDetailDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseQuestionDetailDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseQuestionDetailDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageInfoResponseQuestionDetailDto
     */
    statusCode: number;
    /**
     * 
     * @type {PageInfoResponseQuestionDetailDto}
     * @memberof ApiResponsePageInfoResponseQuestionDetailDto
     */
    data?: PageInfoResponseQuestionDetailDto | null;
}

/**
 * Check if a given object implements the ApiResponsePageInfoResponseQuestionDetailDto interface.
 */
export function instanceOfApiResponsePageInfoResponseQuestionDetailDto(value: object): value is ApiResponsePageInfoResponseQuestionDetailDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponsePageInfoResponseQuestionDetailDtoFromJSON(json: any): ApiResponsePageInfoResponseQuestionDetailDto {
    return ApiResponsePageInfoResponseQuestionDetailDtoFromJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseQuestionDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageInfoResponseQuestionDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : PageInfoResponseQuestionDetailDtoFromJSON(json['data']),
    };
}

export function ApiResponsePageInfoResponseQuestionDetailDtoToJSON(json: any): ApiResponsePageInfoResponseQuestionDetailDto {
    return ApiResponsePageInfoResponseQuestionDetailDtoToJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseQuestionDetailDtoToJSONTyped(value?: ApiResponsePageInfoResponseQuestionDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': PageInfoResponseQuestionDetailDtoToJSON(value['data']),
    };
}

