/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfoResponseAssessmentDetailDto } from './PageInfoResponseAssessmentDetailDto';
import {
    PageInfoResponseAssessmentDetailDtoFromJSON,
    PageInfoResponseAssessmentDetailDtoFromJSONTyped,
    PageInfoResponseAssessmentDetailDtoToJSON,
    PageInfoResponseAssessmentDetailDtoToJSONTyped,
} from './PageInfoResponseAssessmentDetailDto';

/**
 * 
 * @export
 * @interface ApiResponsePageInfoResponseAssessmentDetailDto
 */
export interface ApiResponsePageInfoResponseAssessmentDetailDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseAssessmentDetailDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseAssessmentDetailDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageInfoResponseAssessmentDetailDto
     */
    statusCode: number;
    /**
     * 
     * @type {PageInfoResponseAssessmentDetailDto}
     * @memberof ApiResponsePageInfoResponseAssessmentDetailDto
     */
    data?: PageInfoResponseAssessmentDetailDto | null;
}

/**
 * Check if a given object implements the ApiResponsePageInfoResponseAssessmentDetailDto interface.
 */
export function instanceOfApiResponsePageInfoResponseAssessmentDetailDto(value: object): value is ApiResponsePageInfoResponseAssessmentDetailDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponsePageInfoResponseAssessmentDetailDtoFromJSON(json: any): ApiResponsePageInfoResponseAssessmentDetailDto {
    return ApiResponsePageInfoResponseAssessmentDetailDtoFromJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseAssessmentDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageInfoResponseAssessmentDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : PageInfoResponseAssessmentDetailDtoFromJSON(json['data']),
    };
}

export function ApiResponsePageInfoResponseAssessmentDetailDtoToJSON(json: any): ApiResponsePageInfoResponseAssessmentDetailDto {
    return ApiResponsePageInfoResponseAssessmentDetailDtoToJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseAssessmentDetailDtoToJSONTyped(value?: ApiResponsePageInfoResponseAssessmentDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': PageInfoResponseAssessmentDetailDtoToJSON(value['data']),
    };
}

