/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileDto } from './FileDto';
import {
    FileDtoFromJSON,
    FileDtoFromJSONTyped,
    FileDtoToJSON,
    FileDtoToJSONTyped,
} from './FileDto';

/**
 * 
 * @export
 * @interface ApiResponseFileDto
 */
export interface ApiResponseFileDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseFileDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseFileDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseFileDto
     */
    statusCode: number;
    /**
     * 
     * @type {FileDto}
     * @memberof ApiResponseFileDto
     */
    data?: FileDto;
}

/**
 * Check if a given object implements the ApiResponseFileDto interface.
 */
export function instanceOfApiResponseFileDto(value: object): value is ApiResponseFileDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseFileDtoFromJSON(json: any): ApiResponseFileDto {
    return ApiResponseFileDtoFromJSONTyped(json, false);
}

export function ApiResponseFileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseFileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : FileDtoFromJSON(json['data']),
    };
}

export function ApiResponseFileDtoToJSON(json: any): ApiResponseFileDto {
    return ApiResponseFileDtoToJSONTyped(json, false);
}

export function ApiResponseFileDtoToJSONTyped(value?: ApiResponseFileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': FileDtoToJSON(value['data']),
    };
}

