/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponseStudentAssessmentDto
 */
export interface ApiResponseStudentAssessmentDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseStudentAssessmentDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseStudentAssessmentDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseStudentAssessmentDto
     */
    statusCode: number;
    /**
     * 
     * @type {object}
     * @memberof ApiResponseStudentAssessmentDto
     */
    data?: object | null;
}

/**
 * Check if a given object implements the ApiResponseStudentAssessmentDto interface.
 */
export function instanceOfApiResponseStudentAssessmentDto(value: object): value is ApiResponseStudentAssessmentDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseStudentAssessmentDtoFromJSON(json: any): ApiResponseStudentAssessmentDto {
    return ApiResponseStudentAssessmentDtoFromJSONTyped(json, false);
}

export function ApiResponseStudentAssessmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseStudentAssessmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ApiResponseStudentAssessmentDtoToJSON(json: any): ApiResponseStudentAssessmentDto {
    return ApiResponseStudentAssessmentDtoToJSONTyped(json, false);
}

export function ApiResponseStudentAssessmentDtoToJSONTyped(value?: ApiResponseStudentAssessmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': value['data'],
    };
}

