/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfoResponseClassRoomDto } from './PageInfoResponseClassRoomDto';
import {
    PageInfoResponseClassRoomDtoFromJSON,
    PageInfoResponseClassRoomDtoFromJSONTyped,
    PageInfoResponseClassRoomDtoToJSON,
    PageInfoResponseClassRoomDtoToJSONTyped,
} from './PageInfoResponseClassRoomDto';

/**
 * 
 * @export
 * @interface ApiResponsePageInfoResponseClassRoomDto
 */
export interface ApiResponsePageInfoResponseClassRoomDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseClassRoomDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseClassRoomDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageInfoResponseClassRoomDto
     */
    statusCode: number;
    /**
     * 
     * @type {PageInfoResponseClassRoomDto}
     * @memberof ApiResponsePageInfoResponseClassRoomDto
     */
    data?: PageInfoResponseClassRoomDto | null;
}

/**
 * Check if a given object implements the ApiResponsePageInfoResponseClassRoomDto interface.
 */
export function instanceOfApiResponsePageInfoResponseClassRoomDto(value: object): value is ApiResponsePageInfoResponseClassRoomDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponsePageInfoResponseClassRoomDtoFromJSON(json: any): ApiResponsePageInfoResponseClassRoomDto {
    return ApiResponsePageInfoResponseClassRoomDtoFromJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseClassRoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageInfoResponseClassRoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : PageInfoResponseClassRoomDtoFromJSON(json['data']),
    };
}

export function ApiResponsePageInfoResponseClassRoomDtoToJSON(json: any): ApiResponsePageInfoResponseClassRoomDto {
    return ApiResponsePageInfoResponseClassRoomDtoToJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseClassRoomDtoToJSONTyped(value?: ApiResponsePageInfoResponseClassRoomDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': PageInfoResponseClassRoomDtoToJSON(value['data']),
    };
}

