/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
    UserDtoToJSONTyped,
} from './UserDto';

/**
 * 
 * @export
 * @interface ApiResponseUserDto
 */
export interface ApiResponseUserDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseUserDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseUserDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseUserDto
     */
    statusCode: number;
    /**
     * 
     * @type {UserDto}
     * @memberof ApiResponseUserDto
     */
    data?: UserDto;
}

/**
 * Check if a given object implements the ApiResponseUserDto interface.
 */
export function instanceOfApiResponseUserDto(value: object): value is ApiResponseUserDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseUserDtoFromJSON(json: any): ApiResponseUserDto {
    return ApiResponseUserDtoFromJSONTyped(json, false);
}

export function ApiResponseUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : UserDtoFromJSON(json['data']),
    };
}

export function ApiResponseUserDtoToJSON(json: any): ApiResponseUserDto {
    return ApiResponseUserDtoToJSONTyped(json, false);
}

export function ApiResponseUserDtoToJSONTyped(value?: ApiResponseUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': UserDtoToJSON(value['data']),
    };
}

