/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudyMaterialDto } from './StudyMaterialDto';
import {
    StudyMaterialDtoFromJSON,
    StudyMaterialDtoFromJSONTyped,
    StudyMaterialDtoToJSON,
    StudyMaterialDtoToJSONTyped,
} from './StudyMaterialDto';

/**
 * 
 * @export
 * @interface ApiResponseStudyMaterialDto
 */
export interface ApiResponseStudyMaterialDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseStudyMaterialDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseStudyMaterialDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseStudyMaterialDto
     */
    statusCode: number;
    /**
     * 
     * @type {StudyMaterialDto}
     * @memberof ApiResponseStudyMaterialDto
     */
    data?: StudyMaterialDto | null;
}

/**
 * Check if a given object implements the ApiResponseStudyMaterialDto interface.
 */
export function instanceOfApiResponseStudyMaterialDto(value: object): value is ApiResponseStudyMaterialDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseStudyMaterialDtoFromJSON(json: any): ApiResponseStudyMaterialDto {
    return ApiResponseStudyMaterialDtoFromJSONTyped(json, false);
}

export function ApiResponseStudyMaterialDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseStudyMaterialDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : StudyMaterialDtoFromJSON(json['data']),
    };
}

export function ApiResponseStudyMaterialDtoToJSON(json: any): ApiResponseStudyMaterialDto {
    return ApiResponseStudyMaterialDtoToJSONTyped(json, false);
}

export function ApiResponseStudyMaterialDtoToJSONTyped(value?: ApiResponseStudyMaterialDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': StudyMaterialDtoToJSON(value['data']),
    };
}

