/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleDto } from './ScheduleDto';
import {
    ScheduleDtoFromJSON,
    ScheduleDtoFromJSONTyped,
    ScheduleDtoToJSON,
    ScheduleDtoToJSONTyped,
} from './ScheduleDto';

/**
 * 
 * @export
 * @interface ApiResponseScheduleDto
 */
export interface ApiResponseScheduleDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseScheduleDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseScheduleDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseScheduleDto
     */
    statusCode: number;
    /**
     * 
     * @type {ScheduleDto}
     * @memberof ApiResponseScheduleDto
     */
    data?: ScheduleDto | null;
}

/**
 * Check if a given object implements the ApiResponseScheduleDto interface.
 */
export function instanceOfApiResponseScheduleDto(value: object): value is ApiResponseScheduleDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseScheduleDtoFromJSON(json: any): ApiResponseScheduleDto {
    return ApiResponseScheduleDtoFromJSONTyped(json, false);
}

export function ApiResponseScheduleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseScheduleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : ScheduleDtoFromJSON(json['data']),
    };
}

export function ApiResponseScheduleDtoToJSON(json: any): ApiResponseScheduleDto {
    return ApiResponseScheduleDtoToJSONTyped(json, false);
}

export function ApiResponseScheduleDtoToJSONTyped(value?: ApiResponseScheduleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': ScheduleDtoToJSON(value['data']),
    };
}

