/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentAssessmentItemDto } from './StudentAssessmentItemDto';
import {
    StudentAssessmentItemDtoFromJSON,
    StudentAssessmentItemDtoFromJSONTyped,
    StudentAssessmentItemDtoToJSON,
    StudentAssessmentItemDtoToJSONTyped,
} from './StudentAssessmentItemDto';

/**
 * 
 * @export
 * @interface ApiResponseStudentAssessmentItemDto
 */
export interface ApiResponseStudentAssessmentItemDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseStudentAssessmentItemDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseStudentAssessmentItemDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseStudentAssessmentItemDto
     */
    statusCode: number;
    /**
     * 
     * @type {StudentAssessmentItemDto}
     * @memberof ApiResponseStudentAssessmentItemDto
     */
    data?: StudentAssessmentItemDto | null;
}

/**
 * Check if a given object implements the ApiResponseStudentAssessmentItemDto interface.
 */
export function instanceOfApiResponseStudentAssessmentItemDto(value: object): value is ApiResponseStudentAssessmentItemDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseStudentAssessmentItemDtoFromJSON(json: any): ApiResponseStudentAssessmentItemDto {
    return ApiResponseStudentAssessmentItemDtoFromJSONTyped(json, false);
}

export function ApiResponseStudentAssessmentItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseStudentAssessmentItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : StudentAssessmentItemDtoFromJSON(json['data']),
    };
}

export function ApiResponseStudentAssessmentItemDtoToJSON(json: any): ApiResponseStudentAssessmentItemDto {
    return ApiResponseStudentAssessmentItemDtoToJSONTyped(json, false);
}

export function ApiResponseStudentAssessmentItemDtoToJSONTyped(value?: ApiResponseStudentAssessmentItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': StudentAssessmentItemDtoToJSON(value['data']),
    };
}

