/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookDto } from './BookDto';
import {
    BookDtoFromJSON,
    BookDtoFromJSONTyped,
    BookDtoToJSON,
    BookDtoToJSONTyped,
} from './BookDto';

/**
 * 
 * @export
 * @interface ApiResponseBookDto
 */
export interface ApiResponseBookDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseBookDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseBookDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseBookDto
     */
    statusCode: number;
    /**
     * 
     * @type {BookDto}
     * @memberof ApiResponseBookDto
     */
    data?: BookDto;
}

/**
 * Check if a given object implements the ApiResponseBookDto interface.
 */
export function instanceOfApiResponseBookDto(value: object): value is ApiResponseBookDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseBookDtoFromJSON(json: any): ApiResponseBookDto {
    return ApiResponseBookDtoFromJSONTyped(json, false);
}

export function ApiResponseBookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseBookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : BookDtoFromJSON(json['data']),
    };
}

export function ApiResponseBookDtoToJSON(json: any): ApiResponseBookDto {
    return ApiResponseBookDtoToJSONTyped(json, false);
}

export function ApiResponseBookDtoToJSONTyped(value?: ApiResponseBookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': BookDtoToJSON(value['data']),
    };
}

