/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
    LoginResponseToJSONTyped,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface ApiResponseLoginResponse
 */
export interface ApiResponseLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseLoginResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseLoginResponse
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseLoginResponse
     */
    statusCode: number;
    /**
     * 
     * @type {LoginResponse}
     * @memberof ApiResponseLoginResponse
     */
    data?: LoginResponse | null;
}

/**
 * Check if a given object implements the ApiResponseLoginResponse interface.
 */
export function instanceOfApiResponseLoginResponse(value: object): value is ApiResponseLoginResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseLoginResponseFromJSON(json: any): ApiResponseLoginResponse {
    return ApiResponseLoginResponseFromJSONTyped(json, false);
}

export function ApiResponseLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
    };
}

export function ApiResponseLoginResponseToJSON(json: any): ApiResponseLoginResponse {
    return ApiResponseLoginResponseToJSONTyped(json, false);
}

export function ApiResponseLoginResponseToJSONTyped(value?: ApiResponseLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': LoginResponseToJSON(value['data']),
    };
}

