/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfoResponseBookDto } from './PageInfoResponseBookDto';
import {
    PageInfoResponseBookDtoFromJSON,
    PageInfoResponseBookDtoFromJSONTyped,
    PageInfoResponseBookDtoToJSON,
    PageInfoResponseBookDtoToJSONTyped,
} from './PageInfoResponseBookDto';

/**
 * 
 * @export
 * @interface ApiResponsePageInfoResponseBookDto
 */
export interface ApiResponsePageInfoResponseBookDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseBookDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseBookDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageInfoResponseBookDto
     */
    statusCode: number;
    /**
     * 
     * @type {PageInfoResponseBookDto}
     * @memberof ApiResponsePageInfoResponseBookDto
     */
    data?: PageInfoResponseBookDto | null;
}

/**
 * Check if a given object implements the ApiResponsePageInfoResponseBookDto interface.
 */
export function instanceOfApiResponsePageInfoResponseBookDto(value: object): value is ApiResponsePageInfoResponseBookDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponsePageInfoResponseBookDtoFromJSON(json: any): ApiResponsePageInfoResponseBookDto {
    return ApiResponsePageInfoResponseBookDtoFromJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseBookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageInfoResponseBookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : PageInfoResponseBookDtoFromJSON(json['data']),
    };
}

export function ApiResponsePageInfoResponseBookDtoToJSON(json: any): ApiResponsePageInfoResponseBookDto {
    return ApiResponsePageInfoResponseBookDtoToJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseBookDtoToJSONTyped(value?: ApiResponsePageInfoResponseBookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': PageInfoResponseBookDtoToJSON(value['data']),
    };
}

