/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClassRoomDto } from './ClassRoomDto';
import {
    ClassRoomDtoFromJSON,
    ClassRoomDtoFromJSONTyped,
    ClassRoomDtoToJSON,
    ClassRoomDtoToJSONTyped,
} from './ClassRoomDto';

/**
 * 
 * @export
 * @interface ApiResponseClassRoomDto
 */
export interface ApiResponseClassRoomDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseClassRoomDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseClassRoomDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseClassRoomDto
     */
    statusCode: number;
    /**
     * 
     * @type {ClassRoomDto}
     * @memberof ApiResponseClassRoomDto
     */
    data?: ClassRoomDto | null;
}

/**
 * Check if a given object implements the ApiResponseClassRoomDto interface.
 */
export function instanceOfApiResponseClassRoomDto(value: object): value is ApiResponseClassRoomDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseClassRoomDtoFromJSON(json: any): ApiResponseClassRoomDto {
    return ApiResponseClassRoomDtoFromJSONTyped(json, false);
}

export function ApiResponseClassRoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseClassRoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : ClassRoomDtoFromJSON(json['data']),
    };
}

export function ApiResponseClassRoomDtoToJSON(json: any): ApiResponseClassRoomDto {
    return ApiResponseClassRoomDtoToJSONTyped(json, false);
}

export function ApiResponseClassRoomDtoToJSONTyped(value?: ApiResponseClassRoomDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': ClassRoomDtoToJSON(value['data']),
    };
}

