/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckOutResponse } from './CheckOutResponse';
import {
    CheckOutResponseFromJSON,
    CheckOutResponseFromJSONTyped,
    CheckOutResponseToJSON,
    CheckOutResponseToJSONTyped,
} from './CheckOutResponse';

/**
 * 
 * @export
 * @interface ApiResponseCheckOutResponse
 */
export interface ApiResponseCheckOutResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseCheckOutResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseCheckOutResponse
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseCheckOutResponse
     */
    statusCode: number;
    /**
     * 
     * @type {CheckOutResponse}
     * @memberof ApiResponseCheckOutResponse
     */
    data?: CheckOutResponse | null;
}

/**
 * Check if a given object implements the ApiResponseCheckOutResponse interface.
 */
export function instanceOfApiResponseCheckOutResponse(value: object): value is ApiResponseCheckOutResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseCheckOutResponseFromJSON(json: any): ApiResponseCheckOutResponse {
    return ApiResponseCheckOutResponseFromJSONTyped(json, false);
}

export function ApiResponseCheckOutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseCheckOutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : CheckOutResponseFromJSON(json['data']),
    };
}

export function ApiResponseCheckOutResponseToJSON(json: any): ApiResponseCheckOutResponse {
    return ApiResponseCheckOutResponseToJSONTyped(json, false);
}

export function ApiResponseCheckOutResponseToJSONTyped(value?: ApiResponseCheckOutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': CheckOutResponseToJSON(value['data']),
    };
}

