/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponseListStudentAssessmentDto
 */
export interface ApiResponseListStudentAssessmentDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListStudentAssessmentDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListStudentAssessmentDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListStudentAssessmentDto
     */
    statusCode: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiResponseListStudentAssessmentDto
     */
    data?: Array<object> | null;
}

/**
 * Check if a given object implements the ApiResponseListStudentAssessmentDto interface.
 */
export function instanceOfApiResponseListStudentAssessmentDto(value: object): value is ApiResponseListStudentAssessmentDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseListStudentAssessmentDtoFromJSON(json: any): ApiResponseListStudentAssessmentDto {
    return ApiResponseListStudentAssessmentDtoFromJSONTyped(json, false);
}

export function ApiResponseListStudentAssessmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListStudentAssessmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ApiResponseListStudentAssessmentDtoToJSON(json: any): ApiResponseListStudentAssessmentDto {
    return ApiResponseListStudentAssessmentDtoToJSONTyped(json, false);
}

export function ApiResponseListStudentAssessmentDtoToJSONTyped(value?: ApiResponseListStudentAssessmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': value['data'],
    };
}

