/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfoResponseAssessmentItemDetailDto } from './PageInfoResponseAssessmentItemDetailDto';
import {
    PageInfoResponseAssessmentItemDetailDtoFromJSON,
    PageInfoResponseAssessmentItemDetailDtoFromJSONTyped,
    PageInfoResponseAssessmentItemDetailDtoToJSON,
    PageInfoResponseAssessmentItemDetailDtoToJSONTyped,
} from './PageInfoResponseAssessmentItemDetailDto';

/**
 * 
 * @export
 * @interface ApiResponsePageInfoResponseAssessmentItemDetailDto
 */
export interface ApiResponsePageInfoResponseAssessmentItemDetailDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseAssessmentItemDetailDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageInfoResponseAssessmentItemDetailDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageInfoResponseAssessmentItemDetailDto
     */
    statusCode: number;
    /**
     * 
     * @type {PageInfoResponseAssessmentItemDetailDto}
     * @memberof ApiResponsePageInfoResponseAssessmentItemDetailDto
     */
    data?: PageInfoResponseAssessmentItemDetailDto | null;
}

/**
 * Check if a given object implements the ApiResponsePageInfoResponseAssessmentItemDetailDto interface.
 */
export function instanceOfApiResponsePageInfoResponseAssessmentItemDetailDto(value: object): value is ApiResponsePageInfoResponseAssessmentItemDetailDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponsePageInfoResponseAssessmentItemDetailDtoFromJSON(json: any): ApiResponsePageInfoResponseAssessmentItemDetailDto {
    return ApiResponsePageInfoResponseAssessmentItemDetailDtoFromJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseAssessmentItemDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageInfoResponseAssessmentItemDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : PageInfoResponseAssessmentItemDetailDtoFromJSON(json['data']),
    };
}

export function ApiResponsePageInfoResponseAssessmentItemDetailDtoToJSON(json: any): ApiResponsePageInfoResponseAssessmentItemDetailDto {
    return ApiResponsePageInfoResponseAssessmentItemDetailDtoToJSONTyped(json, false);
}

export function ApiResponsePageInfoResponseAssessmentItemDetailDtoToJSONTyped(value?: ApiResponsePageInfoResponseAssessmentItemDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': PageInfoResponseAssessmentItemDetailDtoToJSON(value['data']),
    };
}

