/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiResponseAssessmentBaseDto
 */
export interface ApiResponseAssessmentBaseDto {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseAssessmentBaseDto
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseAssessmentBaseDto
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseAssessmentBaseDto
     */
    statusCode: number;
    /**
     * 
     * @type {object}
     * @memberof ApiResponseAssessmentBaseDto
     */
    data?: object | null;
}

/**
 * Check if a given object implements the ApiResponseAssessmentBaseDto interface.
 */
export function instanceOfApiResponseAssessmentBaseDto(value: object): value is ApiResponseAssessmentBaseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseAssessmentBaseDtoFromJSON(json: any): ApiResponseAssessmentBaseDto {
    return ApiResponseAssessmentBaseDtoFromJSONTyped(json, false);
}

export function ApiResponseAssessmentBaseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseAssessmentBaseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ApiResponseAssessmentBaseDtoToJSON(json: any): ApiResponseAssessmentBaseDto {
    return ApiResponseAssessmentBaseDtoToJSONTyped(json, false);
}

export function ApiResponseAssessmentBaseDtoToJSONTyped(value?: ApiResponseAssessmentBaseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': value['data'],
    };
}

