/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckInResponse } from './CheckInResponse';
import {
    CheckInResponseFromJSON,
    CheckInResponseFromJSONTyped,
    CheckInResponseToJSON,
    CheckInResponseToJSONTyped,
} from './CheckInResponse';

/**
 * 
 * @export
 * @interface ApiResponseCheckInResponse
 */
export interface ApiResponseCheckInResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseCheckInResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseCheckInResponse
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseCheckInResponse
     */
    statusCode: number;
    /**
     * 
     * @type {CheckInResponse}
     * @memberof ApiResponseCheckInResponse
     */
    data?: CheckInResponse | null;
}

/**
 * Check if a given object implements the ApiResponseCheckInResponse interface.
 */
export function instanceOfApiResponseCheckInResponse(value: object): value is ApiResponseCheckInResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    return true;
}

export function ApiResponseCheckInResponseFromJSON(json: any): ApiResponseCheckInResponse {
    return ApiResponseCheckInResponseFromJSONTyped(json, false);
}

export function ApiResponseCheckInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseCheckInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'],
        'data': json['data'] == null ? undefined : CheckInResponseFromJSON(json['data']),
    };
}

export function ApiResponseCheckInResponseToJSON(json: any): ApiResponseCheckInResponse {
    return ApiResponseCheckInResponseToJSONTyped(json, false);
}

export function ApiResponseCheckInResponseToJSONTyped(value?: ApiResponseCheckInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
        'data': CheckInResponseToJSON(value['data']),
    };
}

