/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookCategoryDto
 */
export interface BookCategoryDto {
    /**
     * 
     * @type {number}
     * @memberof BookCategoryDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BookCategoryDto
     */
    name: string;
}

/**
 * Check if a given object implements the BookCategoryDto interface.
 */
export function instanceOfBookCategoryDto(value: object): value is BookCategoryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BookCategoryDtoFromJSON(json: any): BookCategoryDto {
    return BookCategoryDtoFromJSONTyped(json, false);
}

export function BookCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function BookCategoryDtoToJSON(json: any): BookCategoryDto {
    return BookCategoryDtoToJSONTyped(json, false);
}

export function BookCategoryDtoToJSONTyped(value?: BookCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

