/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckInResponse
 */
export interface CheckInResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CheckInResponse
     */
    late?: boolean;
}

/**
 * Check if a given object implements the CheckInResponse interface.
 */
export function instanceOfCheckInResponse(value: object): value is CheckInResponse {
    return true;
}

export function CheckInResponseFromJSON(json: any): CheckInResponse {
    return CheckInResponseFromJSONTyped(json, false);
}

export function CheckInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'late': json['late'] == null ? undefined : json['late'],
    };
}

export function CheckInResponseToJSON(json: any): CheckInResponse {
    return CheckInResponseToJSONTyped(json, false);
}

export function CheckInResponseToJSONTyped(value?: CheckInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'late': value['late'],
    };
}

