/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckOutResponse
 */
export interface CheckOutResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CheckOutResponse
     */
    earlyLeave?: boolean;
}

/**
 * Check if a given object implements the CheckOutResponse interface.
 */
export function instanceOfCheckOutResponse(value: object): value is CheckOutResponse {
    return true;
}

export function CheckOutResponseFromJSON(json: any): CheckOutResponse {
    return CheckOutResponseFromJSONTyped(json, false);
}

export function CheckOutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckOutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'earlyLeave': json['earlyLeave'] == null ? undefined : json['earlyLeave'],
    };
}

export function CheckOutResponseToJSON(json: any): CheckOutResponse {
    return CheckOutResponseToJSONTyped(json, false);
}

export function CheckOutResponseToJSONTyped(value?: CheckOutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'earlyLeave': value['earlyLeave'],
    };
}

