/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAssessmentItemRequest
 */
export interface CreateAssessmentItemRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateAssessmentItemRequest
     */
    questionId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateAssessmentItemRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAssessmentItemRequest
     */
    order: number;
    /**
     * 
     * @type {string}
     * @memberof CreateAssessmentItemRequest
     */
    type?: CreateAssessmentItemRequestTypeEnum;
}


/**
 * @export
 */
export const CreateAssessmentItemRequestTypeEnum = {
    Question: 'QUESTION'
} as const;
export type CreateAssessmentItemRequestTypeEnum = typeof CreateAssessmentItemRequestTypeEnum[keyof typeof CreateAssessmentItemRequestTypeEnum];


/**
 * Check if a given object implements the CreateAssessmentItemRequest interface.
 */
export function instanceOfCreateAssessmentItemRequest(value: object): value is CreateAssessmentItemRequest {
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function CreateAssessmentItemRequestFromJSON(json: any): CreateAssessmentItemRequest {
    return CreateAssessmentItemRequestFromJSONTyped(json, false);
}

export function CreateAssessmentItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAssessmentItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function CreateAssessmentItemRequestToJSON(json: any): CreateAssessmentItemRequest {
    return CreateAssessmentItemRequestToJSONTyped(json, false);
}

export function CreateAssessmentItemRequestToJSONTyped(value?: CreateAssessmentItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'description': value['description'],
        'order': value['order'],
        'type': value['type'],
    };
}

