/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBatchStudentAssessmentRequest
 */
export interface CreateBatchStudentAssessmentRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateBatchStudentAssessmentRequest
     */
    studentIds?: Array<number>;
}

/**
 * Check if a given object implements the CreateBatchStudentAssessmentRequest interface.
 */
export function instanceOfCreateBatchStudentAssessmentRequest(value: object): value is CreateBatchStudentAssessmentRequest {
    return true;
}

export function CreateBatchStudentAssessmentRequestFromJSON(json: any): CreateBatchStudentAssessmentRequest {
    return CreateBatchStudentAssessmentRequestFromJSONTyped(json, false);
}

export function CreateBatchStudentAssessmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBatchStudentAssessmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'studentIds': json['studentIds'] == null ? undefined : json['studentIds'],
    };
}

export function CreateBatchStudentAssessmentRequestToJSON(json: any): CreateBatchStudentAssessmentRequest {
    return CreateBatchStudentAssessmentRequestToJSONTyped(json, false);
}

export function CreateBatchStudentAssessmentRequestToJSONTyped(value?: CreateBatchStudentAssessmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentIds': value['studentIds'],
    };
}

