/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookRequest
 */
export interface CreateBookRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBookRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookRequest
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookRequest
     */
    isbn: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookRequest
     */
    publisher: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookRequest
     */
    language: string;
    /**
     * 
     * @type {Set<number>}
     * @memberof CreateBookRequest
     */
    categoryIds: Set<number>;
}

/**
 * Check if a given object implements the CreateBookRequest interface.
 */
export function instanceOfCreateBookRequest(value: object): value is CreateBookRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('isbn' in value) || value['isbn'] === undefined) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('categoryIds' in value) || value['categoryIds'] === undefined) return false;
    return true;
}

export function CreateBookRequestFromJSON(json: any): CreateBookRequest {
    return CreateBookRequestFromJSONTyped(json, false);
}

export function CreateBookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'author': json['author'],
        'isbn': json['isbn'],
        'publisher': json['publisher'],
        'language': json['language'],
        'categoryIds': new Set(json['categoryIds']),
    };
}

export function CreateBookRequestToJSON(json: any): CreateBookRequest {
    return CreateBookRequestToJSONTyped(json, false);
}

export function CreateBookRequestToJSONTyped(value?: CreateBookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'author': value['author'],
        'isbn': value['isbn'],
        'publisher': value['publisher'],
        'language': value['language'],
        'categoryIds': Array.from(value['categoryIds'] as Set<any>),
    };
}

