/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMultipleChoiceOptionRequest
 */
export interface CreateMultipleChoiceOptionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateMultipleChoiceOptionRequest
     */
    label?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateMultipleChoiceOptionRequest
     */
    order: number;
}

/**
 * Check if a given object implements the CreateMultipleChoiceOptionRequest interface.
 */
export function instanceOfCreateMultipleChoiceOptionRequest(value: object): value is CreateMultipleChoiceOptionRequest {
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function CreateMultipleChoiceOptionRequestFromJSON(json: any): CreateMultipleChoiceOptionRequest {
    return CreateMultipleChoiceOptionRequestFromJSONTyped(json, false);
}

export function CreateMultipleChoiceOptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMultipleChoiceOptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'order': json['order'],
    };
}

export function CreateMultipleChoiceOptionRequestToJSON(json: any): CreateMultipleChoiceOptionRequest {
    return CreateMultipleChoiceOptionRequestToJSONTyped(json, false);
}

export function CreateMultipleChoiceOptionRequestToJSONTyped(value?: CreateMultipleChoiceOptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'order': value['order'],
    };
}

