/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookFileRequest
 */
export interface CreateBookFileRequest {
    /**
     * 
     * @type {Blob}
     * @memberof CreateBookFileRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the CreateBookFileRequest interface.
 */
export function instanceOfCreateBookFileRequest(value: object): value is CreateBookFileRequest {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function CreateBookFileRequestFromJSON(json: any): CreateBookFileRequest {
    return CreateBookFileRequestFromJSONTyped(json, false);
}

export function CreateBookFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function CreateBookFileRequestToJSON(json: any): CreateBookFileRequest {
    return CreateBookFileRequestToJSONTyped(json, false);
}

export function CreateBookFileRequestToJSONTyped(value?: CreateBookFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

