/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookCategoryRequest
 */
export interface CreateBookCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBookCategoryRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateBookCategoryRequest interface.
 */
export function instanceOfCreateBookCategoryRequest(value: object): value is CreateBookCategoryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateBookCategoryRequestFromJSON(json: any): CreateBookCategoryRequest {
    return CreateBookCategoryRequestFromJSONTyped(json, false);
}

export function CreateBookCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateBookCategoryRequestToJSON(json: any): CreateBookCategoryRequest {
    return CreateBookCategoryRequestToJSONTyped(json, false);
}

export function CreateBookCategoryRequestToJSONTyped(value?: CreateBookCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

