/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateClassRoomRequest
 */
export interface CreateClassRoomRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateClassRoomRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateClassRoomRequest
     */
    teacherId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateClassRoomRequest
     */
    studentIds: Array<number>;
}

/**
 * Check if a given object implements the CreateClassRoomRequest interface.
 */
export function instanceOfCreateClassRoomRequest(value: object): value is CreateClassRoomRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('teacherId' in value) || value['teacherId'] === undefined) return false;
    if (!('studentIds' in value) || value['studentIds'] === undefined) return false;
    return true;
}

export function CreateClassRoomRequestFromJSON(json: any): CreateClassRoomRequest {
    return CreateClassRoomRequestFromJSONTyped(json, false);
}

export function CreateClassRoomRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClassRoomRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'teacherId': json['teacherId'],
        'studentIds': json['studentIds'],
    };
}

export function CreateClassRoomRequestToJSON(json: any): CreateClassRoomRequest {
    return CreateClassRoomRequestToJSONTyped(json, false);
}

export function CreateClassRoomRequestToJSONTyped(value?: CreateClassRoomRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'teacherId': value['teacherId'],
        'studentIds': value['studentIds'],
    };
}

