/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrUpdateAssignedStudentAssessmentItemRequest
 */
export interface CreateOrUpdateAssignedStudentAssessmentItemRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateOrUpdateAssignedStudentAssessmentItemRequest
     */
    assessmentItemId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateAssignedStudentAssessmentItemRequest
     */
    answerText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateOrUpdateAssignedStudentAssessmentItemRequest
     */
    multipleChoiceOptionAnswerId?: number | null;
}

/**
 * Check if a given object implements the CreateOrUpdateAssignedStudentAssessmentItemRequest interface.
 */
export function instanceOfCreateOrUpdateAssignedStudentAssessmentItemRequest(value: object): value is CreateOrUpdateAssignedStudentAssessmentItemRequest {
    return true;
}

export function CreateOrUpdateAssignedStudentAssessmentItemRequestFromJSON(json: any): CreateOrUpdateAssignedStudentAssessmentItemRequest {
    return CreateOrUpdateAssignedStudentAssessmentItemRequestFromJSONTyped(json, false);
}

export function CreateOrUpdateAssignedStudentAssessmentItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrUpdateAssignedStudentAssessmentItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assessmentItemId': json['assessmentItemId'] == null ? undefined : json['assessmentItemId'],
        'answerText': json['answerText'] == null ? undefined : json['answerText'],
        'multipleChoiceOptionAnswerId': json['multipleChoiceOptionAnswerId'] == null ? undefined : json['multipleChoiceOptionAnswerId'],
    };
}

export function CreateOrUpdateAssignedStudentAssessmentItemRequestToJSON(json: any): CreateOrUpdateAssignedStudentAssessmentItemRequest {
    return CreateOrUpdateAssignedStudentAssessmentItemRequestToJSONTyped(json, false);
}

export function CreateOrUpdateAssignedStudentAssessmentItemRequestToJSONTyped(value?: CreateOrUpdateAssignedStudentAssessmentItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assessmentItemId': value['assessmentItemId'],
        'answerText': value['answerText'],
        'multipleChoiceOptionAnswerId': value['multipleChoiceOptionAnswerId'],
    };
}

