/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateScheduleRequest
 */
export interface CreateScheduleRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    classRoomId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    teacherId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateScheduleRequest
     */
    subjectId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateScheduleRequest
     */
    studentIds: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof CreateScheduleRequest
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof CreateScheduleRequest
     */
    endTime: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateScheduleRequest
     */
    date: Date;
}

/**
 * Check if a given object implements the CreateScheduleRequest interface.
 */
export function instanceOfCreateScheduleRequest(value: object): value is CreateScheduleRequest {
    if (!('classRoomId' in value) || value['classRoomId'] === undefined) return false;
    if (!('teacherId' in value) || value['teacherId'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('studentIds' in value) || value['studentIds'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function CreateScheduleRequestFromJSON(json: any): CreateScheduleRequest {
    return CreateScheduleRequestFromJSONTyped(json, false);
}

export function CreateScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateScheduleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'classRoomId': json['classRoomId'],
        'teacherId': json['teacherId'],
        'subjectId': json['subjectId'],
        'studentIds': json['studentIds'],
        'startTime': json['startTime'],
        'endTime': json['endTime'],
        'date': (new Date(json['date'])),
    };
}

export function CreateScheduleRequestToJSON(json: any): CreateScheduleRequest {
    return CreateScheduleRequestToJSONTyped(json, false);
}

export function CreateScheduleRequestToJSONTyped(value?: CreateScheduleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classRoomId': value['classRoomId'],
        'teacherId': value['teacherId'],
        'subjectId': value['subjectId'],
        'studentIds': value['studentIds'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'date': ((value['date']).toISOString().substring(0,10)),
    };
}

