/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookPhotosRequest
 */
export interface CreateBookPhotosRequest {
    /**
     * Photo files, size must be equal with photoOrders
     * @type {Array<Blob>}
     * @memberof CreateBookPhotosRequest
     */
    photos?: Array<Blob>;
    /**
     * Photo file orders, size must be equal with newPhotos
     * @type {Array<number>}
     * @memberof CreateBookPhotosRequest
     */
    photoOrders?: Array<number>;
}

/**
 * Check if a given object implements the CreateBookPhotosRequest interface.
 */
export function instanceOfCreateBookPhotosRequest(value: object): value is CreateBookPhotosRequest {
    return true;
}

export function CreateBookPhotosRequestFromJSON(json: any): CreateBookPhotosRequest {
    return CreateBookPhotosRequestFromJSONTyped(json, false);
}

export function CreateBookPhotosRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookPhotosRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'photos': json['photos'] == null ? undefined : json['photos'],
        'photoOrders': json['photoOrders'] == null ? undefined : json['photoOrders'],
    };
}

export function CreateBookPhotosRequestToJSON(json: any): CreateBookPhotosRequest {
    return CreateBookPhotosRequestToJSONTyped(json, false);
}

export function CreateBookPhotosRequestToJSONTyped(value?: CreateBookPhotosRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'photos': value['photos'],
        'photoOrders': value['photoOrders'],
    };
}

