/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBookPhotosRequest
 */
export interface DeleteBookPhotosRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof DeleteBookPhotosRequest
     */
    photoIds?: Array<number>;
}

/**
 * Check if a given object implements the DeleteBookPhotosRequest interface.
 */
export function instanceOfDeleteBookPhotosRequest(value: object): value is DeleteBookPhotosRequest {
    return true;
}

export function DeleteBookPhotosRequestFromJSON(json: any): DeleteBookPhotosRequest {
    return DeleteBookPhotosRequestFromJSONTyped(json, false);
}

export function DeleteBookPhotosRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBookPhotosRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'photoIds': json['photoIds'] == null ? undefined : json['photoIds'],
    };
}

export function DeleteBookPhotosRequestToJSON(json: any): DeleteBookPhotosRequest {
    return DeleteBookPhotosRequestToJSONTyped(json, false);
}

export function DeleteBookPhotosRequestToJSONTyped(value?: DeleteBookPhotosRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'photoIds': value['photoIds'],
    };
}

