/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBatchStudentAssessmentRequest
 */
export interface DeleteBatchStudentAssessmentRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof DeleteBatchStudentAssessmentRequest
     */
    studentAssessmentIds?: Array<number>;
}

/**
 * Check if a given object implements the DeleteBatchStudentAssessmentRequest interface.
 */
export function instanceOfDeleteBatchStudentAssessmentRequest(value: object): value is DeleteBatchStudentAssessmentRequest {
    return true;
}

export function DeleteBatchStudentAssessmentRequestFromJSON(json: any): DeleteBatchStudentAssessmentRequest {
    return DeleteBatchStudentAssessmentRequestFromJSONTyped(json, false);
}

export function DeleteBatchStudentAssessmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBatchStudentAssessmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'studentAssessmentIds': json['studentAssessmentIds'] == null ? undefined : json['studentAssessmentIds'],
    };
}

export function DeleteBatchStudentAssessmentRequestToJSON(json: any): DeleteBatchStudentAssessmentRequest {
    return DeleteBatchStudentAssessmentRequestToJSONTyped(json, false);
}

export function DeleteBatchStudentAssessmentRequestToJSONTyped(value?: DeleteBatchStudentAssessmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentAssessmentIds': value['studentAssessmentIds'],
    };
}

