/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileOrderDto
 */
export interface FileOrderDto {
    /**
     * 
     * @type {number}
     * @memberof FileOrderDto
     */
    fileId: number;
    /**
     * 
     * @type {number}
     * @memberof FileOrderDto
     */
    order: number;
}

/**
 * Check if a given object implements the FileOrderDto interface.
 */
export function instanceOfFileOrderDto(value: object): value is FileOrderDto {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function FileOrderDtoFromJSON(json: any): FileOrderDto {
    return FileOrderDtoFromJSONTyped(json, false);
}

export function FileOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileOrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'],
        'order': json['order'],
    };
}

export function FileOrderDtoToJSON(json: any): FileOrderDto {
    return FileOrderDtoToJSONTyped(json, false);
}

export function FileOrderDtoToJSONTyped(value?: FileOrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileId': value['fileId'],
        'order': value['order'],
    };
}

