/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAssessmentItemsFilter
 */
export interface GetAssessmentItemsFilter {
    /**
     * 
     * @type {string}
     * @memberof GetAssessmentItemsFilter
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAssessmentItemsFilter
     */
    type?: GetAssessmentItemsFilterTypeEnum | null;
}


/**
 * @export
 */
export const GetAssessmentItemsFilterTypeEnum = {
    Question: 'QUESTION'
} as const;
export type GetAssessmentItemsFilterTypeEnum = typeof GetAssessmentItemsFilterTypeEnum[keyof typeof GetAssessmentItemsFilterTypeEnum];


/**
 * Check if a given object implements the GetAssessmentItemsFilter interface.
 */
export function instanceOfGetAssessmentItemsFilter(value: object): value is GetAssessmentItemsFilter {
    return true;
}

export function GetAssessmentItemsFilterFromJSON(json: any): GetAssessmentItemsFilter {
    return GetAssessmentItemsFilterFromJSONTyped(json, false);
}

export function GetAssessmentItemsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssessmentItemsFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function GetAssessmentItemsFilterToJSON(json: any): GetAssessmentItemsFilter {
    return GetAssessmentItemsFilterToJSONTyped(json, false);
}

export function GetAssessmentItemsFilterToJSONTyped(value?: GetAssessmentItemsFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'type': value['type'],
    };
}

