/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAssessmentsFilter
 */
export interface GetAssessmentsFilter {
    /**
     * 
     * @type {number}
     * @memberof GetAssessmentsFilter
     */
    subjectId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetAssessmentsFilter
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAssessmentsFilter
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAssessmentsFilter
     */
    type?: GetAssessmentsFilterTypeEnum | null;
    /**
     * 
     * @type {string}
     * @memberof GetAssessmentsFilter
     */
    status?: GetAssessmentsFilterStatusEnum | null;
    /**
     * 
     * @type {Date}
     * @memberof GetAssessmentsFilter
     */
    startAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GetAssessmentsFilter
     */
    endAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetAssessmentsFilter
     */
    randomOrder?: boolean | null;
}


/**
 * @export
 */
export const GetAssessmentsFilterTypeEnum = {
    Homework: 'HOMEWORK',
    Quiz: 'QUIZ',
    Uts: 'UTS',
    Uas: 'UAS',
    Remedial: 'REMEDIAL'
} as const;
export type GetAssessmentsFilterTypeEnum = typeof GetAssessmentsFilterTypeEnum[keyof typeof GetAssessmentsFilterTypeEnum];

/**
 * @export
 */
export const GetAssessmentsFilterStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;
export type GetAssessmentsFilterStatusEnum = typeof GetAssessmentsFilterStatusEnum[keyof typeof GetAssessmentsFilterStatusEnum];


/**
 * Check if a given object implements the GetAssessmentsFilter interface.
 */
export function instanceOfGetAssessmentsFilter(value: object): value is GetAssessmentsFilter {
    return true;
}

export function GetAssessmentsFilterFromJSON(json: any): GetAssessmentsFilter {
    return GetAssessmentsFilterFromJSONTyped(json, false);
}

export function GetAssessmentsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssessmentsFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'subjectId': json['subjectId'] == null ? undefined : json['subjectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'startAt': json['startAt'] == null ? undefined : (new Date(json['startAt'])),
        'endAt': json['endAt'] == null ? undefined : (new Date(json['endAt'])),
        'randomOrder': json['randomOrder'] == null ? undefined : json['randomOrder'],
    };
}

export function GetAssessmentsFilterToJSON(json: any): GetAssessmentsFilter {
    return GetAssessmentsFilterToJSONTyped(json, false);
}

export function GetAssessmentsFilterToJSONTyped(value?: GetAssessmentsFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subjectId': value['subjectId'],
        'title': value['title'],
        'description': value['description'],
        'type': value['type'],
        'status': value['status'],
        'startAt': value['startAt'] == null ? undefined : ((value['startAt'] as any).toISOString()),
        'endAt': value['endAt'] == null ? undefined : ((value['endAt'] as any).toISOString()),
        'randomOrder': value['randomOrder'],
    };
}

