/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBooksFilter
 */
export interface GetBooksFilter {
    /**
     * 
     * @type {string}
     * @memberof GetBooksFilter
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBooksFilter
     */
    author?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBooksFilter
     */
    publisher?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBooksFilter
     */
    isbn?: string | null;
    /**
     * 
     * @type {Set<number | null>}
     * @memberof GetBooksFilter
     */
    categoryIds?: Set<number | null> | null;
}

/**
 * Check if a given object implements the GetBooksFilter interface.
 */
export function instanceOfGetBooksFilter(value: object): value is GetBooksFilter {
    return true;
}

export function GetBooksFilterFromJSON(json: any): GetBooksFilter {
    return GetBooksFilterFromJSONTyped(json, false);
}

export function GetBooksFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBooksFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'author': json['author'] == null ? undefined : json['author'],
        'publisher': json['publisher'] == null ? undefined : json['publisher'],
        'isbn': json['isbn'] == null ? undefined : json['isbn'],
        'categoryIds': json['categoryIds'] == null ? undefined : new Set(json['categoryIds']),
    };
}

export function GetBooksFilterToJSON(json: any): GetBooksFilter {
    return GetBooksFilterToJSONTyped(json, false);
}

export function GetBooksFilterToJSONTyped(value?: GetBooksFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'author': value['author'],
        'publisher': value['publisher'],
        'isbn': value['isbn'],
        'categoryIds': value['categoryIds'] == null ? undefined : Array.from(value['categoryIds'] as Set<any>),
    };
}

