/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBookCategoriesFilter
 */
export interface GetBookCategoriesFilter {
    /**
     * 
     * @type {string}
     * @memberof GetBookCategoriesFilter
     */
    name?: string | null;
}

/**
 * Check if a given object implements the GetBookCategoriesFilter interface.
 */
export function instanceOfGetBookCategoriesFilter(value: object): value is GetBookCategoriesFilter {
    return true;
}

export function GetBookCategoriesFilterFromJSON(json: any): GetBookCategoriesFilter {
    return GetBookCategoriesFilterFromJSONTyped(json, false);
}

export function GetBookCategoriesFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBookCategoriesFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetBookCategoriesFilterToJSON(json: any): GetBookCategoriesFilter {
    return GetBookCategoriesFilterToJSONTyped(json, false);
}

export function GetBookCategoriesFilterToJSONTyped(value?: GetBookCategoriesFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

