/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetClassRoomsFilter
 */
export interface GetClassRoomsFilter {
    /**
     * 
     * @type {string}
     * @memberof GetClassRoomsFilter
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetClassRoomsFilter
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetClassRoomsFilter
     */
    homeroomTeacherId?: number | null;
}

/**
 * Check if a given object implements the GetClassRoomsFilter interface.
 */
export function instanceOfGetClassRoomsFilter(value: object): value is GetClassRoomsFilter {
    return true;
}

export function GetClassRoomsFilterFromJSON(json: any): GetClassRoomsFilter {
    return GetClassRoomsFilterFromJSONTyped(json, false);
}

export function GetClassRoomsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClassRoomsFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'homeroomTeacherId': json['homeroomTeacherId'] == null ? undefined : json['homeroomTeacherId'],
    };
}

export function GetClassRoomsFilterToJSON(json: any): GetClassRoomsFilter {
    return GetClassRoomsFilterToJSONTyped(json, false);
}

export function GetClassRoomsFilterToJSONTyped(value?: GetClassRoomsFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'homeroomTeacherId': value['homeroomTeacherId'],
    };
}

