/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetClassRoomsRequest
 */
export interface GetClassRoomsRequest {
    /**
     * 
     * @type {number}
     * @memberof GetClassRoomsRequest
     */
    schoolId?: number | null;
}

/**
 * Check if a given object implements the GetClassRoomsRequest interface.
 */
export function instanceOfGetClassRoomsRequest(value: object): value is GetClassRoomsRequest {
    return true;
}

export function GetClassRoomsRequestFromJSON(json: any): GetClassRoomsRequest {
    return GetClassRoomsRequestFromJSONTyped(json, false);
}

export function GetClassRoomsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClassRoomsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolId': json['schoolId'] == null ? undefined : json['schoolId'],
    };
}

export function GetClassRoomsRequestToJSON(json: any): GetClassRoomsRequest {
    return GetClassRoomsRequestToJSONTyped(json, false);
}

export function GetClassRoomsRequestToJSONTyped(value?: GetClassRoomsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schoolId': value['schoolId'],
    };
}

