/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetQuestionsFilter
 */
export interface GetQuestionsFilter {
    /**
     * 
     * @type {string}
     * @memberof GetQuestionsFilter
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetQuestionsFilter
     */
    type?: GetQuestionsFilterTypeEnum | null;
}


/**
 * @export
 */
export const GetQuestionsFilterTypeEnum = {
    FreeResponse: 'FREE_RESPONSE',
    MultipleChoice: 'MULTIPLE_CHOICE'
} as const;
export type GetQuestionsFilterTypeEnum = typeof GetQuestionsFilterTypeEnum[keyof typeof GetQuestionsFilterTypeEnum];


/**
 * Check if a given object implements the GetQuestionsFilter interface.
 */
export function instanceOfGetQuestionsFilter(value: object): value is GetQuestionsFilter {
    return true;
}

export function GetQuestionsFilterFromJSON(json: any): GetQuestionsFilter {
    return GetQuestionsFilterFromJSONTyped(json, false);
}

export function GetQuestionsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetQuestionsFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function GetQuestionsFilterToJSON(json: any): GetQuestionsFilter {
    return GetQuestionsFilterToJSONTyped(json, false);
}

export function GetQuestionsFilterToJSONTyped(value?: GetQuestionsFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'type': value['type'],
    };
}

