/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStudentAssessmentsFilter
 */
export interface GetStudentAssessmentsFilter {
    /**
     * 
     * @type {Array<number | null>}
     * @memberof GetStudentAssessmentsFilter
     */
    studentIds?: Array<number | null> | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetStudentAssessmentsFilter
     */
    isRetake?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof GetStudentAssessmentsFilter
     */
    status?: GetStudentAssessmentsFilterStatusEnum | null;
}


/**
 * @export
 */
export const GetStudentAssessmentsFilterStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Submitted: 'SUBMITTED',
    Graded: 'GRADED'
} as const;
export type GetStudentAssessmentsFilterStatusEnum = typeof GetStudentAssessmentsFilterStatusEnum[keyof typeof GetStudentAssessmentsFilterStatusEnum];


/**
 * Check if a given object implements the GetStudentAssessmentsFilter interface.
 */
export function instanceOfGetStudentAssessmentsFilter(value: object): value is GetStudentAssessmentsFilter {
    return true;
}

export function GetStudentAssessmentsFilterFromJSON(json: any): GetStudentAssessmentsFilter {
    return GetStudentAssessmentsFilterFromJSONTyped(json, false);
}

export function GetStudentAssessmentsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStudentAssessmentsFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'studentIds': json['studentIds'] == null ? undefined : json['studentIds'],
        'isRetake': json['isRetake'] == null ? undefined : json['isRetake'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function GetStudentAssessmentsFilterToJSON(json: any): GetStudentAssessmentsFilter {
    return GetStudentAssessmentsFilterToJSONTyped(json, false);
}

export function GetStudentAssessmentsFilterToJSONTyped(value?: GetStudentAssessmentsFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentIds': value['studentIds'],
        'isRetake': value['isRetake'],
        'status': value['status'],
    };
}

