/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSubjectsFilter
 */
export interface GetSubjectsFilter {
    /**
     * 
     * @type {string}
     * @memberof GetSubjectsFilter
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSubjectsFilter
     */
    gradeLevel?: string | null;
}

/**
 * Check if a given object implements the GetSubjectsFilter interface.
 */
export function instanceOfGetSubjectsFilter(value: object): value is GetSubjectsFilter {
    return true;
}

export function GetSubjectsFilterFromJSON(json: any): GetSubjectsFilter {
    return GetSubjectsFilterFromJSONTyped(json, false);
}

export function GetSubjectsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubjectsFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'gradeLevel': json['gradeLevel'] == null ? undefined : json['gradeLevel'],
    };
}

export function GetSubjectsFilterToJSON(json: any): GetSubjectsFilter {
    return GetSubjectsFilterToJSONTyped(json, false);
}

export function GetSubjectsFilterToJSONTyped(value?: GetSubjectsFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'gradeLevel': value['gradeLevel'],
    };
}

