/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GradeStudentAssessmentRequest
 */
export interface GradeStudentAssessmentRequest {
    /**
     * 
     * @type {number}
     * @memberof GradeStudentAssessmentRequest
     */
    score?: number;
}

/**
 * Check if a given object implements the GradeStudentAssessmentRequest interface.
 */
export function instanceOfGradeStudentAssessmentRequest(value: object): value is GradeStudentAssessmentRequest {
    return true;
}

export function GradeStudentAssessmentRequestFromJSON(json: any): GradeStudentAssessmentRequest {
    return GradeStudentAssessmentRequestFromJSONTyped(json, false);
}

export function GradeStudentAssessmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GradeStudentAssessmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
    };
}

export function GradeStudentAssessmentRequestToJSON(json: any): GradeStudentAssessmentRequest {
    return GradeStudentAssessmentRequestToJSONTyped(json, false);
}

export function GradeStudentAssessmentRequestToJSONTyped(value?: GradeStudentAssessmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
    };
}

