/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultipleChoiceOptionDto
 */
export interface MultipleChoiceOptionDto {
    /**
     * 
     * @type {number}
     * @memberof MultipleChoiceOptionDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MultipleChoiceOptionDto
     */
    label?: string;
    /**
     * 
     * @type {number}
     * @memberof MultipleChoiceOptionDto
     */
    order?: number;
}

/**
 * Check if a given object implements the MultipleChoiceOptionDto interface.
 */
export function instanceOfMultipleChoiceOptionDto(value: object): value is MultipleChoiceOptionDto {
    return true;
}

export function MultipleChoiceOptionDtoFromJSON(json: any): MultipleChoiceOptionDto {
    return MultipleChoiceOptionDtoFromJSONTyped(json, false);
}

export function MultipleChoiceOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleChoiceOptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function MultipleChoiceOptionDtoToJSON(json: any): MultipleChoiceOptionDto {
    return MultipleChoiceOptionDtoToJSONTyped(json, false);
}

export function MultipleChoiceOptionDtoToJSONTyped(value?: MultipleChoiceOptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'order': value['order'],
    };
}

