/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookDto } from './BookDto';
import {
    BookDtoFromJSON,
    BookDtoFromJSONTyped,
    BookDtoToJSON,
    BookDtoToJSONTyped,
} from './BookDto';

/**
 * 
 * @export
 * @interface PageInfoResponseBookDto
 */
export interface PageInfoResponseBookDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<BookDto>}
     * @memberof PageInfoResponseBookDto
     */
    content?: Array<BookDto>;
}

/**
 * Check if a given object implements the PageInfoResponseBookDto interface.
 */
export function instanceOfPageInfoResponseBookDto(value: object): value is PageInfoResponseBookDto {
    return true;
}

export function PageInfoResponseBookDtoFromJSON(json: any): PageInfoResponseBookDto {
    return PageInfoResponseBookDtoFromJSONTyped(json, false);
}

export function PageInfoResponseBookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseBookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(BookDtoFromJSON)),
    };
}

export function PageInfoResponseBookDtoToJSON(json: any): PageInfoResponseBookDto {
    return PageInfoResponseBookDtoToJSONTyped(json, false);
}

export function PageInfoResponseBookDtoToJSONTyped(value?: PageInfoResponseBookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(BookDtoToJSON)),
    };
}

