/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageInfoResponseAssessmentDetailDto
 */
export interface PageInfoResponseAssessmentDetailDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentDetailDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentDetailDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentDetailDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentDetailDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof PageInfoResponseAssessmentDetailDto
     */
    content?: Array<object>;
}

/**
 * Check if a given object implements the PageInfoResponseAssessmentDetailDto interface.
 */
export function instanceOfPageInfoResponseAssessmentDetailDto(value: object): value is PageInfoResponseAssessmentDetailDto {
    return true;
}

export function PageInfoResponseAssessmentDetailDtoFromJSON(json: any): PageInfoResponseAssessmentDetailDto {
    return PageInfoResponseAssessmentDetailDtoFromJSONTyped(json, false);
}

export function PageInfoResponseAssessmentDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseAssessmentDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function PageInfoResponseAssessmentDetailDtoToJSON(json: any): PageInfoResponseAssessmentDetailDto {
    return PageInfoResponseAssessmentDetailDtoToJSONTyped(json, false);
}

export function PageInfoResponseAssessmentDetailDtoToJSONTyped(value?: PageInfoResponseAssessmentDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'],
    };
}

