/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionDetailDto } from './QuestionDetailDto';
import {
    QuestionDetailDtoFromJSON,
    QuestionDetailDtoFromJSONTyped,
    QuestionDetailDtoToJSON,
    QuestionDetailDtoToJSONTyped,
} from './QuestionDetailDto';

/**
 * 
 * @export
 * @interface PageInfoResponseQuestionDetailDto
 */
export interface PageInfoResponseQuestionDetailDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseQuestionDetailDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseQuestionDetailDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseQuestionDetailDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseQuestionDetailDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<QuestionDetailDto>}
     * @memberof PageInfoResponseQuestionDetailDto
     */
    content?: Array<QuestionDetailDto>;
}

/**
 * Check if a given object implements the PageInfoResponseQuestionDetailDto interface.
 */
export function instanceOfPageInfoResponseQuestionDetailDto(value: object): value is PageInfoResponseQuestionDetailDto {
    return true;
}

export function PageInfoResponseQuestionDetailDtoFromJSON(json: any): PageInfoResponseQuestionDetailDto {
    return PageInfoResponseQuestionDetailDtoFromJSONTyped(json, false);
}

export function PageInfoResponseQuestionDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseQuestionDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(QuestionDetailDtoFromJSON)),
    };
}

export function PageInfoResponseQuestionDetailDtoToJSON(json: any): PageInfoResponseQuestionDetailDto {
    return PageInfoResponseQuestionDetailDtoToJSONTyped(json, false);
}

export function PageInfoResponseQuestionDetailDtoToJSONTyped(value?: PageInfoResponseQuestionDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(QuestionDetailDtoToJSON)),
    };
}

