/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentAssessmentItemDto } from './StudentAssessmentItemDto';
import {
    StudentAssessmentItemDtoFromJSON,
    StudentAssessmentItemDtoFromJSONTyped,
    StudentAssessmentItemDtoToJSON,
    StudentAssessmentItemDtoToJSONTyped,
} from './StudentAssessmentItemDto';

/**
 * 
 * @export
 * @interface PageInfoResponseStudentAssessmentItemDto
 */
export interface PageInfoResponseStudentAssessmentItemDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentItemDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentItemDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentItemDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentItemDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<StudentAssessmentItemDto>}
     * @memberof PageInfoResponseStudentAssessmentItemDto
     */
    content?: Array<StudentAssessmentItemDto>;
}

/**
 * Check if a given object implements the PageInfoResponseStudentAssessmentItemDto interface.
 */
export function instanceOfPageInfoResponseStudentAssessmentItemDto(value: object): value is PageInfoResponseStudentAssessmentItemDto {
    return true;
}

export function PageInfoResponseStudentAssessmentItemDtoFromJSON(json: any): PageInfoResponseStudentAssessmentItemDto {
    return PageInfoResponseStudentAssessmentItemDtoFromJSONTyped(json, false);
}

export function PageInfoResponseStudentAssessmentItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseStudentAssessmentItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(StudentAssessmentItemDtoFromJSON)),
    };
}

export function PageInfoResponseStudentAssessmentItemDtoToJSON(json: any): PageInfoResponseStudentAssessmentItemDto {
    return PageInfoResponseStudentAssessmentItemDtoToJSONTyped(json, false);
}

export function PageInfoResponseStudentAssessmentItemDtoToJSONTyped(value?: PageInfoResponseStudentAssessmentItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(StudentAssessmentItemDtoToJSON)),
    };
}

