/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClassRoomDto } from './ClassRoomDto';
import {
    ClassRoomDtoFromJSON,
    ClassRoomDtoFromJSONTyped,
    ClassRoomDtoToJSON,
    ClassRoomDtoToJSONTyped,
} from './ClassRoomDto';

/**
 * 
 * @export
 * @interface PageInfoResponseClassRoomDto
 */
export interface PageInfoResponseClassRoomDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseClassRoomDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseClassRoomDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseClassRoomDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseClassRoomDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<ClassRoomDto>}
     * @memberof PageInfoResponseClassRoomDto
     */
    content?: Array<ClassRoomDto>;
}

/**
 * Check if a given object implements the PageInfoResponseClassRoomDto interface.
 */
export function instanceOfPageInfoResponseClassRoomDto(value: object): value is PageInfoResponseClassRoomDto {
    return true;
}

export function PageInfoResponseClassRoomDtoFromJSON(json: any): PageInfoResponseClassRoomDto {
    return PageInfoResponseClassRoomDtoFromJSONTyped(json, false);
}

export function PageInfoResponseClassRoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseClassRoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ClassRoomDtoFromJSON)),
    };
}

export function PageInfoResponseClassRoomDtoToJSON(json: any): PageInfoResponseClassRoomDto {
    return PageInfoResponseClassRoomDtoToJSONTyped(json, false);
}

export function PageInfoResponseClassRoomDtoToJSONTyped(value?: PageInfoResponseClassRoomDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ClassRoomDtoToJSON)),
    };
}

