/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookCategoryDto } from './BookCategoryDto';
import {
    BookCategoryDtoFromJSON,
    BookCategoryDtoFromJSONTyped,
    BookCategoryDtoToJSON,
    BookCategoryDtoToJSONTyped,
} from './BookCategoryDto';

/**
 * 
 * @export
 * @interface PageInfoResponseBookCategoryDto
 */
export interface PageInfoResponseBookCategoryDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookCategoryDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookCategoryDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookCategoryDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseBookCategoryDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<BookCategoryDto>}
     * @memberof PageInfoResponseBookCategoryDto
     */
    content?: Array<BookCategoryDto>;
}

/**
 * Check if a given object implements the PageInfoResponseBookCategoryDto interface.
 */
export function instanceOfPageInfoResponseBookCategoryDto(value: object): value is PageInfoResponseBookCategoryDto {
    return true;
}

export function PageInfoResponseBookCategoryDtoFromJSON(json: any): PageInfoResponseBookCategoryDto {
    return PageInfoResponseBookCategoryDtoFromJSONTyped(json, false);
}

export function PageInfoResponseBookCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseBookCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(BookCategoryDtoFromJSON)),
    };
}

export function PageInfoResponseBookCategoryDtoToJSON(json: any): PageInfoResponseBookCategoryDto {
    return PageInfoResponseBookCategoryDtoToJSONTyped(json, false);
}

export function PageInfoResponseBookCategoryDtoToJSONTyped(value?: PageInfoResponseBookCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(BookCategoryDtoToJSON)),
    };
}

