/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageInfoResponseStudentAssessmentDto
 */
export interface PageInfoResponseStudentAssessmentDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseStudentAssessmentDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof PageInfoResponseStudentAssessmentDto
     */
    content?: Array<object>;
}

/**
 * Check if a given object implements the PageInfoResponseStudentAssessmentDto interface.
 */
export function instanceOfPageInfoResponseStudentAssessmentDto(value: object): value is PageInfoResponseStudentAssessmentDto {
    return true;
}

export function PageInfoResponseStudentAssessmentDtoFromJSON(json: any): PageInfoResponseStudentAssessmentDto {
    return PageInfoResponseStudentAssessmentDtoFromJSONTyped(json, false);
}

export function PageInfoResponseStudentAssessmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseStudentAssessmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function PageInfoResponseStudentAssessmentDtoToJSON(json: any): PageInfoResponseStudentAssessmentDto {
    return PageInfoResponseStudentAssessmentDtoToJSONTyped(json, false);
}

export function PageInfoResponseStudentAssessmentDtoToJSONTyped(value?: PageInfoResponseStudentAssessmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'],
    };
}

