/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageInfoResponseAssessmentItemDetailDto
 */
export interface PageInfoResponseAssessmentItemDetailDto {
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentItemDetailDto
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentItemDetailDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentItemDetailDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfoResponseAssessmentItemDetailDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof PageInfoResponseAssessmentItemDetailDto
     */
    content?: Array<object>;
}

/**
 * Check if a given object implements the PageInfoResponseAssessmentItemDetailDto interface.
 */
export function instanceOfPageInfoResponseAssessmentItemDetailDto(value: object): value is PageInfoResponseAssessmentItemDetailDto {
    return true;
}

export function PageInfoResponseAssessmentItemDetailDtoFromJSON(json: any): PageInfoResponseAssessmentItemDetailDto {
    return PageInfoResponseAssessmentItemDetailDtoFromJSONTyped(json, false);
}

export function PageInfoResponseAssessmentItemDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfoResponseAssessmentItemDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'number': json['number'] == null ? undefined : json['number'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function PageInfoResponseAssessmentItemDetailDtoToJSON(json: any): PageInfoResponseAssessmentItemDetailDto {
    return PageInfoResponseAssessmentItemDetailDtoToJSONTyped(json, false);
}

export function PageInfoResponseAssessmentItemDetailDtoToJSONTyped(value?: PageInfoResponseAssessmentItemDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'number': value['number'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'content': value['content'],
    };
}

