/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplaceBookFileRequest
 */
export interface ReplaceBookFileRequest {
    /**
     * 
     * @type {Blob}
     * @memberof ReplaceBookFileRequest
     */
    file?: Blob;
}

/**
 * Check if a given object implements the ReplaceBookFileRequest interface.
 */
export function instanceOfReplaceBookFileRequest(value: object): value is ReplaceBookFileRequest {
    return true;
}

export function ReplaceBookFileRequestFromJSON(json: any): ReplaceBookFileRequest {
    return ReplaceBookFileRequestFromJSONTyped(json, false);
}

export function ReplaceBookFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplaceBookFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'] == null ? undefined : json['file'],
    };
}

export function ReplaceBookFileRequestToJSON(json: any): ReplaceBookFileRequest {
    return ReplaceBookFileRequestToJSONTyped(json, false);
}

export function ReplaceBookFileRequestToJSONTyped(value?: ReplaceBookFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

