/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchoolDto
 */
export interface SchoolDto {
    /**
     * 
     * @type {number}
     * @memberof SchoolDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SchoolDto
     */
    name: string;
}

/**
 * Check if a given object implements the SchoolDto interface.
 */
export function instanceOfSchoolDto(value: object): value is SchoolDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SchoolDtoFromJSON(json: any): SchoolDto {
    return SchoolDtoFromJSONTyped(json, false);
}

export function SchoolDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function SchoolDtoToJSON(json: any): SchoolDto {
    return SchoolDtoToJSONTyped(json, false);
}

export function SchoolDtoToJSONTyped(value?: SchoolDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

