/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherDto
 */
export interface TeacherDto {
    /**
     * 
     * @type {number}
     * @memberof TeacherDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TeacherDto
     */
    name: string;
}

/**
 * Check if a given object implements the TeacherDto interface.
 */
export function instanceOfTeacherDto(value: object): value is TeacherDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TeacherDtoFromJSON(json: any): TeacherDto {
    return TeacherDtoFromJSONTyped(json, false);
}

export function TeacherDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function TeacherDtoToJSON(json: any): TeacherDto {
    return TeacherDtoToJSONTyped(json, false);
}

export function TeacherDtoToJSONTyped(value?: TeacherDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

