/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateClassRoomRequest
 */
export interface UpdateClassRoomRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateClassRoomRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateClassRoomRequest
     */
    teacherId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateClassRoomRequest
     */
    studentIds?: Array<number>;
}

/**
 * Check if a given object implements the UpdateClassRoomRequest interface.
 */
export function instanceOfUpdateClassRoomRequest(value: object): value is UpdateClassRoomRequest {
    return true;
}

export function UpdateClassRoomRequestFromJSON(json: any): UpdateClassRoomRequest {
    return UpdateClassRoomRequestFromJSONTyped(json, false);
}

export function UpdateClassRoomRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateClassRoomRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'teacherId': json['teacherId'] == null ? undefined : json['teacherId'],
        'studentIds': json['studentIds'] == null ? undefined : json['studentIds'],
    };
}

export function UpdateClassRoomRequestToJSON(json: any): UpdateClassRoomRequest {
    return UpdateClassRoomRequestToJSONTyped(json, false);
}

export function UpdateClassRoomRequestToJSONTyped(value?: UpdateClassRoomRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'teacherId': value['teacherId'],
        'studentIds': value['studentIds'],
    };
}

