/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSubjectRequest
 */
export interface UpdateSubjectRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSubjectRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSubjectRequest
     */
    gradeLevel?: string;
}

/**
 * Check if a given object implements the UpdateSubjectRequest interface.
 */
export function instanceOfUpdateSubjectRequest(value: object): value is UpdateSubjectRequest {
    return true;
}

export function UpdateSubjectRequestFromJSON(json: any): UpdateSubjectRequest {
    return UpdateSubjectRequestFromJSONTyped(json, false);
}

export function UpdateSubjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSubjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'gradeLevel': json['gradeLevel'] == null ? undefined : json['gradeLevel'],
    };
}

export function UpdateSubjectRequestToJSON(json: any): UpdateSubjectRequest {
    return UpdateSubjectRequestToJSONTyped(json, false);
}

export function UpdateSubjectRequestToJSONTyped(value?: UpdateSubjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'gradeLevel': value['gradeLevel'],
    };
}

