/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileOrderDto } from './FileOrderDto';
import {
    FileOrderDtoFromJSON,
    FileOrderDtoFromJSONTyped,
    FileOrderDtoToJSON,
    FileOrderDtoToJSONTyped,
} from './FileOrderDto';

/**
 * 
 * @export
 * @interface UpdateBookPhotoOrdersRequest
 */
export interface UpdateBookPhotoOrdersRequest {
    /**
     * 
     * @type {Array<FileOrderDto>}
     * @memberof UpdateBookPhotoOrdersRequest
     */
    fileOrders?: Array<FileOrderDto>;
}

/**
 * Check if a given object implements the UpdateBookPhotoOrdersRequest interface.
 */
export function instanceOfUpdateBookPhotoOrdersRequest(value: object): value is UpdateBookPhotoOrdersRequest {
    return true;
}

export function UpdateBookPhotoOrdersRequestFromJSON(json: any): UpdateBookPhotoOrdersRequest {
    return UpdateBookPhotoOrdersRequestFromJSONTyped(json, false);
}

export function UpdateBookPhotoOrdersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBookPhotoOrdersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileOrders': json['fileOrders'] == null ? undefined : ((json['fileOrders'] as Array<any>).map(FileOrderDtoFromJSON)),
    };
}

export function UpdateBookPhotoOrdersRequestToJSON(json: any): UpdateBookPhotoOrdersRequest {
    return UpdateBookPhotoOrdersRequestToJSONTyped(json, false);
}

export function UpdateBookPhotoOrdersRequestToJSONTyped(value?: UpdateBookPhotoOrdersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileOrders': value['fileOrders'] == null ? undefined : ((value['fileOrders'] as Array<any>).map(FileOrderDtoToJSON)),
    };
}

