/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAssessmentItemRequest
 */
export interface UpdateAssessmentItemRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateAssessmentItemRequest
     */
    questionId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssessmentItemRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateAssessmentItemRequest
     */
    order?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssessmentItemRequest
     */
    type?: UpdateAssessmentItemRequestTypeEnum | null;
}


/**
 * @export
 */
export const UpdateAssessmentItemRequestTypeEnum = {
    Question: 'QUESTION'
} as const;
export type UpdateAssessmentItemRequestTypeEnum = typeof UpdateAssessmentItemRequestTypeEnum[keyof typeof UpdateAssessmentItemRequestTypeEnum];


/**
 * Check if a given object implements the UpdateAssessmentItemRequest interface.
 */
export function instanceOfUpdateAssessmentItemRequest(value: object): value is UpdateAssessmentItemRequest {
    return true;
}

export function UpdateAssessmentItemRequestFromJSON(json: any): UpdateAssessmentItemRequest {
    return UpdateAssessmentItemRequestFromJSONTyped(json, false);
}

export function UpdateAssessmentItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAssessmentItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function UpdateAssessmentItemRequestToJSON(json: any): UpdateAssessmentItemRequest {
    return UpdateAssessmentItemRequestToJSONTyped(json, false);
}

export function UpdateAssessmentItemRequestToJSONTyped(value?: UpdateAssessmentItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'description': value['description'],
        'order': value['order'],
        'type': value['type'],
    };
}

