/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBookCategoryRequest
 */
export interface UpdateBookCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateBookCategoryRequest
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateBookCategoryRequest interface.
 */
export function instanceOfUpdateBookCategoryRequest(value: object): value is UpdateBookCategoryRequest {
    return true;
}

export function UpdateBookCategoryRequestFromJSON(json: any): UpdateBookCategoryRequest {
    return UpdateBookCategoryRequestFromJSONTyped(json, false);
}

export function UpdateBookCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBookCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateBookCategoryRequestToJSON(json: any): UpdateBookCategoryRequest {
    return UpdateBookCategoryRequestToJSONTyped(json, false);
}

export function UpdateBookCategoryRequestToJSONTyped(value?: UpdateBookCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

