/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAssessmentRequest
 */
export interface UpdateAssessmentRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateAssessmentRequest
     */
    subjectId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssessmentRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssessmentRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssessmentRequest
     */
    type?: UpdateAssessmentRequestTypeEnum | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssessmentRequest
     */
    status?: UpdateAssessmentRequestStatusEnum | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateAssessmentRequest
     */
    startAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateAssessmentRequest
     */
    endAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateAssessmentRequest
     */
    durationMinutes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateAssessmentRequest
     */
    maxAttempts?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAssessmentRequest
     */
    randomOrder?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateAssessmentRequest
     */
    maxScore?: number | null;
}


/**
 * @export
 */
export const UpdateAssessmentRequestTypeEnum = {
    Homework: 'HOMEWORK',
    Quiz: 'QUIZ',
    Uts: 'UTS',
    Uas: 'UAS',
    Remedial: 'REMEDIAL'
} as const;
export type UpdateAssessmentRequestTypeEnum = typeof UpdateAssessmentRequestTypeEnum[keyof typeof UpdateAssessmentRequestTypeEnum];

/**
 * @export
 */
export const UpdateAssessmentRequestStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;
export type UpdateAssessmentRequestStatusEnum = typeof UpdateAssessmentRequestStatusEnum[keyof typeof UpdateAssessmentRequestStatusEnum];


/**
 * Check if a given object implements the UpdateAssessmentRequest interface.
 */
export function instanceOfUpdateAssessmentRequest(value: object): value is UpdateAssessmentRequest {
    return true;
}

export function UpdateAssessmentRequestFromJSON(json: any): UpdateAssessmentRequest {
    return UpdateAssessmentRequestFromJSONTyped(json, false);
}

export function UpdateAssessmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAssessmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'subjectId': json['subjectId'] == null ? undefined : json['subjectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'startAt': json['startAt'] == null ? undefined : (new Date(json['startAt'])),
        'endAt': json['endAt'] == null ? undefined : (new Date(json['endAt'])),
        'durationMinutes': json['durationMinutes'] == null ? undefined : json['durationMinutes'],
        'maxAttempts': json['maxAttempts'] == null ? undefined : json['maxAttempts'],
        'randomOrder': json['randomOrder'] == null ? undefined : json['randomOrder'],
        'maxScore': json['maxScore'] == null ? undefined : json['maxScore'],
    };
}

export function UpdateAssessmentRequestToJSON(json: any): UpdateAssessmentRequest {
    return UpdateAssessmentRequestToJSONTyped(json, false);
}

export function UpdateAssessmentRequestToJSONTyped(value?: UpdateAssessmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subjectId': value['subjectId'],
        'title': value['title'],
        'description': value['description'],
        'type': value['type'],
        'status': value['status'],
        'startAt': value['startAt'] == null ? undefined : ((value['startAt'] as any).toISOString()),
        'endAt': value['endAt'] == null ? undefined : ((value['endAt'] as any).toISOString()),
        'durationMinutes': value['durationMinutes'],
        'maxAttempts': value['maxAttempts'],
        'randomOrder': value['randomOrder'],
        'maxScore': value['maxScore'],
    };
}

