/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateScheduleRequest
 */
export interface UpdateScheduleRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateScheduleRequest
     */
    classRoomId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateScheduleRequest
     */
    teacherId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateScheduleRequest
     */
    subjectId?: number | null;
    /**
     * 
     * @type {Array<number | null>}
     * @memberof UpdateScheduleRequest
     */
    studentIds?: Array<number | null> | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateScheduleRequest
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateScheduleRequest
     */
    endTime?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateScheduleRequest
     */
    date?: Date | null;
}

/**
 * Check if a given object implements the UpdateScheduleRequest interface.
 */
export function instanceOfUpdateScheduleRequest(value: object): value is UpdateScheduleRequest {
    return true;
}

export function UpdateScheduleRequestFromJSON(json: any): UpdateScheduleRequest {
    return UpdateScheduleRequestFromJSONTyped(json, false);
}

export function UpdateScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateScheduleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'classRoomId': json['classRoomId'] == null ? undefined : json['classRoomId'],
        'teacherId': json['teacherId'] == null ? undefined : json['teacherId'],
        'subjectId': json['subjectId'] == null ? undefined : json['subjectId'],
        'studentIds': json['studentIds'] == null ? undefined : json['studentIds'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
    };
}

export function UpdateScheduleRequestToJSON(json: any): UpdateScheduleRequest {
    return UpdateScheduleRequestToJSONTyped(json, false);
}

export function UpdateScheduleRequestToJSONTyped(value?: UpdateScheduleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classRoomId': value['classRoomId'],
        'teacherId': value['teacherId'],
        'subjectId': value['subjectId'],
        'studentIds': value['studentIds'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'date': value['date'] == null ? undefined : ((value['date'] as any).toISOString().substring(0,10)),
    };
}

