/* tslint:disable */
/* eslint-disable */
/**
 * APSI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMultipleChoiceOptionRequest
 */
export interface UpdateMultipleChoiceOptionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleChoiceOptionRequest
     */
    label?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateMultipleChoiceOptionRequest
     */
    order?: number | null;
}

/**
 * Check if a given object implements the UpdateMultipleChoiceOptionRequest interface.
 */
export function instanceOfUpdateMultipleChoiceOptionRequest(value: object): value is UpdateMultipleChoiceOptionRequest {
    return true;
}

export function UpdateMultipleChoiceOptionRequestFromJSON(json: any): UpdateMultipleChoiceOptionRequest {
    return UpdateMultipleChoiceOptionRequestFromJSONTyped(json, false);
}

export function UpdateMultipleChoiceOptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleChoiceOptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function UpdateMultipleChoiceOptionRequestToJSON(json: any): UpdateMultipleChoiceOptionRequest {
    return UpdateMultipleChoiceOptionRequestToJSONTyped(json, false);
}

export function UpdateMultipleChoiceOptionRequestToJSONTyped(value?: UpdateMultipleChoiceOptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'order': value['order'],
    };
}

